const experienceData = [
  {
    title: "DevOps Engineer",
    company: "ecsec GmbH",
    period: "Sep 2025 – Present",
    location: "Germany",
    highlights: [
      "Designed, deployed, and maintained cloud-native services using Kubernetes, ensuring secure, scalable, and highly available environments across multiple deployments.",
      "Built and optimized containerized microservices with Docker and modern JVM-based frameworks, improving deployment reliability, performance, and consistency across environments.",
      "Engineered multi-tenant architectures supporting dynamic configuration, policy management, and environment-specific deployments.",
      "Integrated advanced cryptographic workflows—such as key management, token handling, and secure exchange mechanisms—into service platforms to enable robust authentication and authorization flows.",
      "Performed extensive interoperability and integration testing with a wide range of client applications and external systems, improving platform compatibility, reliability, and standards alignment.",
      "Developed internal tooling, automation scripts, and test frameworks to accelerate debugging, validation, and development processes.",
      "Implemented and optimized industry-standard protocols to support secure, end-to-end service interactions based on evolving global specifications.",
    ],
  },
  {
    title: "Graduate Researcher",
    company: "Fraunhofer IIS",
    period: "Jan 2022 - Sep 2024",
    location: "Erlangen, Germany",
    highlights: [
      "Developed and deployed the CINGO spatial audio system in Unity 3D, enhancing the user experience in virtual environments by creating modular software for real-time spatial audio rendering",
      "Conducted a comparative analysis of loudspeaker and headphone recordings using sine sweep, analyzing Room Impulse Responses (RIRs) and correlating acoustic measures with perceptual audio quality",
      "Recorded loudspeaker/headphones using sweeps for multiple source-receiver configurations to improve and enhance the RIR dataset",
      "Designed Acoustic Visualization tools using Qt/C++, enabling room acoustics visualization and analysis of large datasets",
      "Enhanced Binaural Room Impulse Responses (BRIRs) and assessed innovative spatial audio plugins, optimizing data-driven audio systems for improved localization, timbre, and envelopment",
      "Played a pivotal role in the Mobile Audio Rendering team, enhancing overall user experience in spatial audio using signal processing",
      "Executed MUSHRA tests to assess spatial audio perceptual effects with HRTF across diverse populations, achieving a 30% improvement in audio quality",
      "Designed and implemented an analysis framework for comparing various spatial binaural renderers, enabling comprehensive comparison and optimization of spatial audio tools",
      "Created a RIR similarity matching algorithm using unsupervised machine learning, automating the comparison of Frequency Domain Network (FDN)-based RIRs with real-world RIRs, improving system efficiency by streamlining data processing",
    ],
  },
  {
    title: "Associate Engineer",
    company: "Tata Consultancy Services",
    period: "Sep 2018 - Jun 2020",
    location: "Pune, India",
    highlights: [
      "Designed and deployed a three-tier web application using Docker, Kubernetes, Jenkins, and AWS EC2, improving deployment efficiency by 40%",
      "Deployed a complete environment, including VPC, EC2 instances, RDS, and S3 buckets, with version-controlled templates",
      "Implemented a CI/CD pipeline using AWS CodePipeline and CodeBuild, automating the deployment of a serverless application with AWS Lambda and S3, reducing deployment time by 30%",
      "Maintained and optimized the Model Data Repository for offshore banking operations with the Bank of Montreal, ensuring high data integrity and performance",
      "Designed data models and implemented complex SQL queries for data extraction, reporting, and analytics, reducing query execution time by 20%",
      "Developed a RESTful API for managing database interactions, integrating DynamoDB for highly available data processing",
      "Standardized infrastructure deployment using AWS CDK and CloudFormation templates, reducing manual configuration errors by 80%",
      "Deployed a production-grade Kubernetes application on AWS EKS, optimizing resource allocation and scaling by 50%",
      "Created Helm charts to streamline deployments and manage versioned updates, achieving seamless rollouts with zero downtime",
      "Automated cluster provisioning and scaling through CI/CD pipelines using GitHub Actions and Terraform, reducing deployment cycles by 60%",
      "Ensured high availability with 99.95% uptime and improved operational efficiency by cutting manual intervention by 45%",
    ],
  },
];

export default experienceData;
